---

jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: aviato-profile
      trigger: true
    - get: version
      params: { pre: rc }
  - task: build
    file: aviato-profile/ci/build.yml
    params:
      MAVEN_OPTS: {{maven-opts}}
      MAVEN_CONFIG: {{maven-config}}
      MAVEN_REPO_MIRROR: {{maven-mirror-url}}
      MAVEN_REPO_USERNAME: {{maven-username}}
      MAVEN_REPO_PASSWORD: {{maven-password}}
      ARTIFACT_GLOB: aviato-profile-*.jar
  - put: maven-milestone
    params:
      file: build-output/aviato-profile-*.jar
      pom_file: aviato-profile/pom.xml
      version_file: version/number
  - put: version
    params:
      file: version/number
  - put: tracker
    params:
      repos:
        - aviato-profile

- name: test
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: maven-milestone
      passed: [ build ]
      trigger: true
  - task: generate-manifest
    file: aviato-profile/ci/generate-manifest.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_SKIP_SSL: {{cf-skip-ssl}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: {{cf-space}}
      CF_APP_NAME: {{cf-app-name}}
      CF_APP_HOST: {{cf-app-host}}
      ARTIFACT_GLOB: aviato-profile-*.jar
  - put: cf-create-org
    resource: cf-itest
    params:
      create_space:
        org: {{cf-org}}
  - put: cf-create-space
    resource: cf-itest
    params:
      create_space:
        org: {{cf-org}}
        space: {{cf-space}}
  - put: cf-create-db
    resource: cf-itest
    params:
      create_service:
        org: {{cf-org}}
        space: {{cf-space}}
        service: "p-mysql"
        plan: "100mb"
        service_instance: "aviato-profile-db"
  - put: cf-push
    resource: cf-itest
    params:
      push:
        org: {{cf-org}}
        space: {{cf-space}}
        manifest: generate-manifest-output/manifest.yml

resources:
- name: aviato-profile
  type: git
  source:
    uri: {{git-uri}}
    branch: master
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: number
    private_key: {{github-private-key}}

- name: maven-milestone
  type: maven-resource
  source:
    url: {{maven-milestone-url}}
    artifact: com.aviato:aviato-profile:jar
    username: {{maven-username}}
    password: {{maven-password}}
    skip_cert_check: true

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}

- name: cf-itest
  type: cf-cli-resource
  source:
    api: {{cf-api-url}}
    skip_cert_check: true
    username: {{cf-username}}
    password: {{cf-password}}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: 1.1.0

- name: cf-cli-resource
  type: docker-image
  source:
    repository: patrickcrocker/cf-cli-resource
    tag: 1.0.0
