# This pipeline requires Concourse 3.3+ for caching features. To fall back to
# an earlier version of Concourse, replace these:
#   "pipeline-tasks/build-maven-semver-cache/task.yml"
#   "pipeline-tasks/run-maven-itests-cache/task.yml"
# with these:
#   "pipeline-tasks/build-maven-semver/task.yml"
#   "pipeline-tasks/run-maven-itests-cache/task.yml"
#
---
groups:
- name: all
  jobs:
  - build
  - test
  - uat
  - shipit
  - patch
  - prod
  - major
  - minor
- name: develop
  jobs:
  - build
  - test
  - uat
- name: publish
  jobs:
  - shipit
  - patch
  - prod
  - major
  - minor

maven-params: &maven-params
  MAVEN_OPTS: {{maven-opts}}
  MAVEN_CONFIG: {{maven-config}}
  MAVEN_REPO_MIRROR: {{maven-mirror-url}}
  MAVEN_REPO_USERNAME: {{maven-mirror-username}}
  MAVEN_REPO_PASSWORD: {{maven-mirror-password}}
  MAVEN_REPO_CACHE_ENABLE: true

jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: project
      resource: aviato-profile
      trigger: true
    - get: version
      params: {pre: rc}
  - task: build
    file: pipeline-tasks/build-maven-semver-cache/task.yml
    params:
      <<: *maven-params
  - put: maven-milestone
    params:
      file: task-output/aviato-profile-*.jar
      pom_file: project/pom.xml
      version_file: version/version
  - put: version
    params: {file: version/version}
  - put: tracker
    params: {repos: [aviato-profile]}

- name: test
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: project
      resource: aviato-profile
      passed: [build]
    - get: version
      passed: [build]
    - get: artifact
      resource: maven-milestone
      passed: [build]
      trigger: true
  - put: cf-prepare-env
    resource: cf-test
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: create-service
        service: {{cf-test-app-db-service}}
        plan: {{cf-test-app-db-plan}}
        service_instance: {{cf-test-app-db-si}}
        wait_for_service: true
  - task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params:
      MF_NAME: {{cf-test-app-name}}
      MF_HOST: {{cf-test-app-host}}
      MF_SERVICES: [{{cf-test-app-db-si}}]
  - put: cf-push
    resource: cf-test
    params:
      command: zero-downtime-push
      manifest: task-output/manifest.yml
      path: artifact/aviato-profile-*.jar
      current_app_name: {{cf-test-app-name}}
  - task: integration-tests
    file: pipeline-tasks/run-maven-itests-cache/task.yml
    params:
      <<: *maven-params
      APP_URL: {{cf-test-app-url}}

- name: uat
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: project
      resource: aviato-profile
      passed: [test]
    - get: version
      passed: [test]
    - get: artifact
      resource: maven-milestone
      passed: [test]
      # trigger: true
  - put: cf-prepare-env
    resource: cf-uat
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: create-service
        service: {{cf-uat-app-db-service}}
        plan: {{cf-uat-app-db-plan}}
        service_instance: {{cf-uat-app-db-si}}
        wait_for_service: true
  - task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params:
      MF_NAME: {{cf-uat-app-name}}
      MF_HOST: {{cf-uat-app-host}}
      MF_SERVICES: [{{cf-uat-app-db-si}}]
  - put: cf-push
    resource: cf-uat
    params:
      command: zero-downtime-push
      manifest: task-output/manifest.yml
      path: artifact/aviato-profile-*.jar
      current_app_name: {{cf-uat-app-name}}
  - task: integration-tests
    file: pipeline-tasks/run-maven-itests-cache/task.yml
    params:
      <<: *maven-params
      APP_URL: {{cf-uat-app-url}}

- name: shipit
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: project
      resource: aviato-profile
      passed: [uat]
    - get: version
      passed: [uat]
      params: {bump: final}
    - get: maven-milestone
      passed: [uat]
  - put: maven-release
    params:
      file: maven-milestone/aviato-profile-*.jar
      pom_file: project/pom.xml
      version_file: version/version
  - put: version
    params: {file: version/version}

- name: prod
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: project
      resource: aviato-profile
      passed: [shipit]
    - get: version
      passed: [shipit]
    - get: artifact
      resource: maven-release
      passed: [shipit]
  - put: cf-prepare-env
    resource: cf-prod
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: create-service
        service: {{cf-prod-app-db-service}}
        plan: {{cf-prod-app-db-plan}}
        service_instance: {{cf-prod-app-db-si}}
        wait_for_service: true
  - task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params:
      MF_NAME: {{cf-prod-app-name}}
      MF_HOST: {{cf-prod-app-host}}
      MF_SERVICES: [{{cf-prod-app-db-si}}]
  - put: cf-push
    resource: cf-prod
    params:
      command: zero-downtime-push
      manifest: task-output/manifest.yml
      path: artifact/aviato-profile-*.jar
      current_app_name: {{cf-prod-app-name}}
  - task: integration-tests
    file: pipeline-tasks/run-maven-itests-cache/task.yml
    params:
      <<: *maven-params
      APP_URL: {{cf-prod-app-url}}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-uri}}
    branch: {{pipeline-tasks-git-branch}}

- name: aviato-profile
  type: git
  source:
    uri: {{git-project-uri}}
    branch: {{git-project-branch}}
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-semver-uri}}
    branch: {{git-semver-branch}}
    file: version
    private_key: {{github-private-key}}

- name: maven-milestone
  type: maven-resource
  source:
    url: {{maven-milestone-url}}
    artifact: com.aviato:aviato-profile:jar
    username: {{maven-milestone-username}}
    password: {{maven-milestone-password}}
    skip_cert_check: {{maven-milestone-skip-ssl}}
    repository_cert: {{maven-milestone-cert}}

- name: maven-release
  type: maven-resource
  source:
    url: {{maven-release-url}}
    artifact: com.aviato:aviato-profile:jar
    username: {{maven-release-username}}
    password: {{maven-release-password}}
    skip_cert_check: {{maven-release-skip-ssl}}
    repository_cert: {{maven-release-cert}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}

- name: cf-test
  type: cf-cli-resource
  source:
    api: {{cf-test-api-url}}
    skip_cert_check: {{cf-test-skip-ssl}}
    username: {{cf-test-username}}
    password: ((cf-test-password))
    org: {{cf-test-org}}
    space: {{cf-test-space}}

- name: cf-uat
  type: cf-cli-resource
  source:
    api: {{cf-uat-api-url}}
    skip_cert_check: {{cf-uat-skip-ssl}}
    username: {{cf-uat-username}}
    password: ((cf-uat-password))
    org: {{cf-uat-org}}
    space: {{cf-uat-space}}

- name: cf-prod
  type: cf-cli-resource
  source:
    api: {{cf-prod-api-url}}
    skip_cert_check: {{cf-prod-skip-ssl}}
    username: {{cf-prod-username}}
    password: ((cf-prod-password))
    org: {{cf-prod-org}}
    space: {{cf-prod-space}}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: 1.3.4

- name: cf-cli-resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: 2.4.0-rc.5
