---
maven-params: &maven-params
  MAVEN_OPTS: {{maven-opts}}
  MAVEN_CONFIG: {{maven-config}}
  MAVEN_REPO_MIRROR: {{maven-mirror-url}}
  MAVEN_REPO_USERNAME: {{maven-username}}
  MAVEN_REPO_PASSWORD: {{maven-password}}

jobs:
- name: build
  public: true
  plan:
  - get: aviato-profile
    trigger: true
  - get: version
    params: { pre: rc }
  - task: build
    file: aviato-profile/ci/build.yml
    params:
      <<: *maven-params
  - put: maven-milestone
    params:
      file: build-output/aviato-profile-*.jar
      version_file: version/number
  - put: version
    params: { file: version/number }
  - put: tracker
    params:
      repos:
        - aviato-profile

- name: test
  public: true
  plan:
  - get: maven-milestone
    trigger: true
    passed: [ build ]
  - get: aviato-profile
    passed: [ build ]
  - get: version
    passed: [ build ]
  - task: prepare-integration
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: '8'
      run:
        path: ls
        args: ["-al", "maven-milestone"]

resources:
- name: aviato-profile
  type: git
  source:
    uri: {{git-uri}}
    branch: master
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: number
    private_key: {{github-private-key}}

- name: maven-milestone
  type: maven-resource
  source:
    url: {{maven-milestone-url}}
    artifact: com.aviato:aviato-profile:jar
    username: {{maven-username}}
    password: {{maven-password}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
