---
maven-params: &maven-params
  MAVEN_OPTS: {{maven-opts}}
  MAVEN_CONFIG: {{maven-config}}

jobs:
- name: build
  public: true
  plan:
  - get: aviato-profile
    trigger: true
  - get: version
    params: { pre: rc }
  - task: build
    file: aviato-profile/ci/build.yml
    params:
      <<: *maven-params
  - put: maven-milestones
    params:
      file: build-output/aviato-profile-*.jar
      groupId: com.aviato
      artifactId: aviato-profile
      version_file: version/number
      packaging: jar
  - put: version
    params: { file: version/number }

resources:
- name: aviato-profile
  type: git
  source:
    uri: {{git-uri}}
    branch: master
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: number
    private_key: {{github-private-key}}

- name: maven-releases
  type: maven-resource
  source:
    url: {{maven-release-repository-url}}
    username: {{maven-repository-username}}
    password: {{maven-repository-password}}

- name: maven-milestones
  type: maven-resource
  source:
    url: {{maven-milestone-repository-url}}
    username: {{maven-repository-username}}
    password: {{maven-repository-password}}

- name: maven-snapshots
  type: maven-resource
  source:
    url: {{maven-snapshot-repository-url}}
    username: {{maven-repository-username}}
    password: {{maven-repository-password}}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
