---
maven-params: &maven-params
  MAVEN_OPTS: {{maven-opts}}
  MAVEN_CONFIG: {{maven-config}}
  MAVEN_REPO_MIRROR: {{maven-mirror-url}}
  MAVEN_REPO_USERNAME: {{maven-username}}
  MAVEN_REPO_PASSWORD: {{maven-password}}

cf-params: &cf-params
  CF_API_URL: {{cf-api-url}}
  CF_SKIP_SSL: {{cf-skip-ssl}}
  CF_USERNAME: {{cf-username}}
  CF_PASSWORD: {{cf-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}

jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: project
      resource: aviato-profile
      trigger: true
    - get: version
      params: { pre: rc }
    - get: concourse-commons
  - task: build
    file: concourse-commons/tasks/build-maven.yml
    params:
      <<: *maven-params
      ARTIFACT_GLOB: aviato-profile-*.jar
  - put: maven-milestone
    params:
      file: build-output/aviato-profile-*.jar
      pom_file: project/pom.xml
      version_file: version/number
  - put: version
    params:
      file: version/number
  - put: tracker
    params:
      repos:
        - aviato-profile

- name: test
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: release
      resource: maven-milestone
      passed: [ build ]
      trigger: true
    - get: concourse-commons
  - task: generate-manifest
    file: concourse-commons/tasks/generate-manifest.yml
    params:
      <<: *cf-params
      CF_APP_NAME: {{cf-app-name}}
      CF_APP_HOST: {{cf-app-host}}
      ARTIFACT_GLOB: aviato-profile-*.jar
  - put: cf-push
    resource: cf-itest
    params:
      create_space:
        org: {{cf-org}}
        space: {{cf-space}}
      create_service:
        org: {{cf-org}}
        space: {{cf-space}}
        service: "cleardb"
        plan: "spark"
        service_instance: "aviato-profile-db"
      push:
        manifest: generate-manifest-output/manifest.yml
        current_app_name: {{cf-app-name}}

resources:
- name: concourse-commons
  type: git
  source:
    uri: {{concourse-commons-git-uri}}
    branch: {{concourse-commons-git-branch}}

- name: aviato-profile
  type: git
  source:
    uri: {{git-uri}}
    branch: master
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: number
    private_key: {{github-private-key}}

- name: maven-milestone
  type: maven-resource
  source:
    url: {{maven-milestone-url}}
    artifact: com.aviato:aviato-profile:jar
    username: {{maven-username}}
    password: {{maven-password}}
    skip_cert_check: true

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}

- name: cf-itest
  type: cf-cli-resource
  source:
    api: {{cf-api-url}}
    skip_cert_check: true
    username: {{cf-username}}
    password: {{cf-password}}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: 1.1.0

- name: cf-cli-resource
  type: docker-image
  source:
    repository: patrickcrocker/cf-cli-resource
    tag: 1.0.0-rc.4
