---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG: 
  MAVEN_BASEDIR: aviato-profile

inputs:
  - name: aviato-profile

run:
  path: aviato-profile/mvnw
  args: [
    "-f", "aviato-profile/pom.xml",
    "clean", "deploy"
  ]
