---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:
  MAVEN_REPO_MIRROR:
  MAVEN_REPO_USERNAME:
  MAVEN_REPO_PASSWORD:

inputs:
  - name: aviato-profile
  - name: version

outputs:
  - name: build-output

run:
  path: aviato-profile/ci/build.sh
