---
resources:
  - name: aviato-profile
    type: git
    source:
      uri: git://10.0.2.2/aviato-profile
      branch: master

jobs:
  - name: unit
    public: true
    plan:
      - get: aviato-profile
        trigger: true
      - task: unit
        file: aviato-profile/ci/tasks/unit.yml
  - name: build
    serial_groups: [ version ]
    plan:
      - get: aviato-profile
        passed: [ unit ]
        trigger: true
      - task: build
        file: aviato-profile/ci/tasks/build.yml
