---
resources:
  - name: aviato-profile
    type: git
    source:
      uri: git://10.0.2.2/aviato-profile
      branch: master

jobs:
  - name: build-snapshot
    public: true
    plan:
      - get: aviato-profile
        trigger: true
      - task: build-snapshot
        file: aviato-profile/ci/tasks/build-snapshot.yml
#        params: &MAVENPARAMS
#          MAVEN_OPTS: { {maven-opts}}
#          MAVEN_CONFIG: { {maven-config}}
