---
resources:
  - name: aviato-profile
    type: git
    source:
      uri: {{git-uri}}
      branch: master
      private_key: {{github-private-key}}

  - name: version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: {{git-uri-semver}}
      branch: version
      file: number
      private_key: {{github-private-key}}

jobs:
  - name: build
    public: true
    plan:
      - get: aviato-profile
        trigger: true
      - get: version
        params: { pre: rc }
      - task: build
        file: aviato-profile/ci/tasks/build.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}
      - put: version
        params: { file: version/number }

  - name: test
    plan:
      - get: aviato-profile
        passed: [ build ]
        trigger: true
      - task: cf-deploy
        file: aviato-profile/ci/tasks/cf-deploy.yml
        params:
          <<: *MAVENPARAMS
