---
resources:
  - name: aviato-profile
    type: git
    source:
      uri: {{git-uri}}
      branch: master
      private_key: {{github-private-key}}

- name: resource-version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-bump-semver}}
    branch: version
    file: version
    private_key: {{github-private-key}}

jobs:
  - name: build-snapshot
    public: true
    plan:
      - get: aviato-profile
        trigger: true
      - task: build-snapshot
        file: aviato-profile/ci/tasks/build-snapshot.yml
#        params: &MAVENPARAMS
#          MAVEN_OPTS: { {maven-opts}}
#          MAVEN_CONFIG: { {maven-config}}
